name: flutter_artist_styles_demo
description: "FlutterArtist Styles Demo"
publish_to: 'none'
version: 1.0.0
homepage: https://o7planning.github.io

environment:
  sdk: ^3.11.5
dependencies:
  flutter:
    sdk: flutter

  flutter_artist_core: ^1.0.0
  flutter_artist_styles: ^2.1.0
  flutter_artist_styles_inspector: ^2.0.5
  flutter_left_right_container: ^0.9.4


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true